/*
* generated by Xtext
*/
package org.artop.ecuc.autosar4x.dsl.values.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EcucValuesDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/artop/ecuc/autosar4x/dsl/values/parser/antlr/internal/InternalEcucValuesDsl.tokens");
	}
}
