/*
* generated by Xtext
*/
package org.artop.ecuc.autosar4x.dsl.values.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.artop.ecuc.autosar4x.dsl.values.services.EcucValuesDslGrammarAccess;

public class EcucValuesDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EcucValuesDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.artop.ecuc.autosar4x.dsl.values.parser.antlr.internal.InternalEcucValuesDslParser createParser(XtextTokenStream stream) {
		return new org.artop.ecuc.autosar4x.dsl.values.parser.antlr.internal.InternalEcucValuesDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public EcucValuesDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EcucValuesDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
