/*
 * generated by Xtext
 */
package org.artop.ecuc.autosar4x.dsl.values.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.artop.ecuc.autosar4x.dsl.values.ui.internal.EcucValuesDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EcucValuesDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EcucValuesDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EcucValuesDslActivator.getInstance().getInjector(EcucValuesDslActivator.ORG_ARTOP_ECUC_AUTOSAR4X_DSL_VALUES_ECUCVALUESDSL);
	}
	
}
