/*
 * generated by Xtext
 */
package org.artop.ecuc.autosar4x.dsl.paramdef.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.artop.ecuc.autosar4x.dsl.paramdef.ui.internal.ParamDefDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ParamDefDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ParamDefDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ParamDefDslActivator.getInstance().getInjector(ParamDefDslActivator.ORG_ARTOP_ECUC_AUTOSAR4X_DSL_PARAMDEF_PARAMDEFDSL);
	}
	
}
