/*
* generated by Xtext
*/
package org.artop.ecuc.autosar4x.dsl.paramdef.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.artop.ecuc.autosar4x.dsl.paramdef.services.ParamDefDslGrammarAccess;

public class ParamDefDslParser extends AbstractContentAssistParser {
	
	@Inject
	private ParamDefDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.artop.ecuc.autosar4x.dsl.paramdef.ui.contentassist.antlr.internal.InternalParamDefDslParser createParser() {
		org.artop.ecuc.autosar4x.dsl.paramdef.ui.contentassist.antlr.internal.InternalParamDefDslParser result = new org.artop.ecuc.autosar4x.dsl.paramdef.ui.contentassist.antlr.internal.InternalParamDefDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAbstractContainerDefAccess().getAlternatives(), "rule__AbstractContainerDef__Alternatives");
					put(grammarAccess.getContainerDefAccess().getAlternatives_2_1_0_1(), "rule__ContainerDef__Alternatives_2_1_0_1");
					put(grammarAccess.getContainerDefAccess().getAlternatives_4(), "rule__ContainerDef__Alternatives_4");
					put(grammarAccess.getContainerElementAccess().getAlternatives(), "rule__ContainerElement__Alternatives");
					put(grammarAccess.getChoiceContainerDefAccess().getAlternatives_2_1_0_1(), "rule__ChoiceContainerDef__Alternatives_2_1_0_1");
					put(grammarAccess.getParameterDefAccess().getAlternatives_4_1_0_1(), "rule__ParameterDef__Alternatives_4_1_0_1");
					put(grammarAccess.getAbstractReferenceDefAccess().getAlternatives(), "rule__AbstractReferenceDef__Alternatives");
					put(grammarAccess.getReferenceDefAccess().getAlternatives_5_1_0_1(), "rule__ReferenceDef__Alternatives_5_1_0_1");
					put(grammarAccess.getInstanceReferenceDefAccess().getAlternatives_6_1_0_1(), "rule__InstanceReferenceDef__Alternatives_6_1_0_1");
					put(grammarAccess.getForeignReferenceDefAccess().getAlternatives_4_1_0_1(), "rule__ForeignReferenceDef__Alternatives_4_1_0_1");
					put(grammarAccess.getVALUEAccess().getAlternatives(), "rule__VALUE__Alternatives");
					put(grammarAccess.getKEYAccess().getAlternatives(), "rule__KEY__Alternatives");
					put(grammarAccess.getUPPER_MULTIPLICITYAccess().getAlternatives(), "rule__UPPER_MULTIPLICITY__Alternatives");
					put(grammarAccess.getParameterTypeAccess().getAlternatives(), "rule__ParameterType__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getModelAccess().getGroup_0(), "rule__Model__Group_0__0");
					put(grammarAccess.getModuleDefAccess().getGroup(), "rule__ModuleDef__Group__0");
					put(grammarAccess.getModuleDefAccess().getGroup_2(), "rule__ModuleDef__Group_2__0");
					put(grammarAccess.getModuleDefAccess().getGroup_2_1_0(), "rule__ModuleDef__Group_2_1_0__0");
					put(grammarAccess.getModuleDefAccess().getGroup_2_1_1(), "rule__ModuleDef__Group_2_1_1__0");
					put(grammarAccess.getModuleDefAccess().getGroup_2_1_1_2(), "rule__ModuleDef__Group_2_1_1_2__0");
					put(grammarAccess.getContainerDefAccess().getGroup(), "rule__ContainerDef__Group__0");
					put(grammarAccess.getContainerDefAccess().getGroup_2(), "rule__ContainerDef__Group_2__0");
					put(grammarAccess.getContainerDefAccess().getGroup_2_1_0(), "rule__ContainerDef__Group_2_1_0__0");
					put(grammarAccess.getContainerDefAccess().getGroup_2_1_1(), "rule__ContainerDef__Group_2_1_1__0");
					put(grammarAccess.getContainerDefAccess().getGroup_2_1_2(), "rule__ContainerDef__Group_2_1_2__0");
					put(grammarAccess.getContainerDefAccess().getGroup_2_1_2_2(), "rule__ContainerDef__Group_2_1_2_2__0");
					put(grammarAccess.getContainerDefAccess().getGroup_2_1_3(), "rule__ContainerDef__Group_2_1_3__0");
					put(grammarAccess.getContainerDefAccess().getGroup_2_1_4(), "rule__ContainerDef__Group_2_1_4__0");
					put(grammarAccess.getChoiceContainerDefAccess().getGroup(), "rule__ChoiceContainerDef__Group__0");
					put(grammarAccess.getChoiceContainerDefAccess().getGroup_2(), "rule__ChoiceContainerDef__Group_2__0");
					put(grammarAccess.getChoiceContainerDefAccess().getGroup_2_1_0(), "rule__ChoiceContainerDef__Group_2_1_0__0");
					put(grammarAccess.getChoiceContainerDefAccess().getGroup_2_1_1(), "rule__ChoiceContainerDef__Group_2_1_1__0");
					put(grammarAccess.getChoiceContainerDefAccess().getGroup_2_1_2(), "rule__ChoiceContainerDef__Group_2_1_2__0");
					put(grammarAccess.getChoiceContainerDefAccess().getGroup_2_1_2_2(), "rule__ChoiceContainerDef__Group_2_1_2_2__0");
					put(grammarAccess.getChoiceContainerDefAccess().getGroup_2_1_3(), "rule__ChoiceContainerDef__Group_2_1_3__0");
					put(grammarAccess.getChoiceContainerDefAccess().getGroup_2_1_4(), "rule__ChoiceContainerDef__Group_2_1_4__0");
					put(grammarAccess.getParameterDefAccess().getGroup(), "rule__ParameterDef__Group__0");
					put(grammarAccess.getParameterDefAccess().getGroup_4(), "rule__ParameterDef__Group_4__0");
					put(grammarAccess.getParameterDefAccess().getGroup_4_1_0(), "rule__ParameterDef__Group_4_1_0__0");
					put(grammarAccess.getParameterDefAccess().getGroup_4_1_1(), "rule__ParameterDef__Group_4_1_1__0");
					put(grammarAccess.getParameterDefAccess().getGroup_4_1_2(), "rule__ParameterDef__Group_4_1_2__0");
					put(grammarAccess.getParameterDefAccess().getGroup_4_1_3(), "rule__ParameterDef__Group_4_1_3__0");
					put(grammarAccess.getParameterDefAccess().getGroup_4_1_4(), "rule__ParameterDef__Group_4_1_4__0");
					put(grammarAccess.getParameterDefAccess().getGroup_4_1_4_2(), "rule__ParameterDef__Group_4_1_4_2__0");
					put(grammarAccess.getParameterDefAccess().getGroup_4_1_5(), "rule__ParameterDef__Group_4_1_5__0");
					put(grammarAccess.getParameterDefAccess().getGroup_4_1_6(), "rule__ParameterDef__Group_4_1_6__0");
					put(grammarAccess.getParameterDefAccess().getGroup_4_1_7(), "rule__ParameterDef__Group_4_1_7__0");
					put(grammarAccess.getParameterDefAccess().getGroup_4_1_8(), "rule__ParameterDef__Group_4_1_8__0");
					put(grammarAccess.getReferenceDefAccess().getGroup(), "rule__ReferenceDef__Group__0");
					put(grammarAccess.getReferenceDefAccess().getGroup_4(), "rule__ReferenceDef__Group_4__0");
					put(grammarAccess.getReferenceDefAccess().getGroup_5(), "rule__ReferenceDef__Group_5__0");
					put(grammarAccess.getReferenceDefAccess().getGroup_5_1_0(), "rule__ReferenceDef__Group_5_1_0__0");
					put(grammarAccess.getReferenceDefAccess().getGroup_5_1_1(), "rule__ReferenceDef__Group_5_1_1__0");
					put(grammarAccess.getReferenceDefAccess().getGroup_5_1_2(), "rule__ReferenceDef__Group_5_1_2__0");
					put(grammarAccess.getReferenceDefAccess().getGroup_5_1_2_2(), "rule__ReferenceDef__Group_5_1_2_2__0");
					put(grammarAccess.getReferenceDefAccess().getGroup_5_1_3(), "rule__ReferenceDef__Group_5_1_3__0");
					put(grammarAccess.getReferenceDefAccess().getGroup_5_1_4(), "rule__ReferenceDef__Group_5_1_4__0");
					put(grammarAccess.getInstanceReferenceDefAccess().getGroup(), "rule__InstanceReferenceDef__Group__0");
					put(grammarAccess.getInstanceReferenceDefAccess().getGroup_3(), "rule__InstanceReferenceDef__Group_3__0");
					put(grammarAccess.getInstanceReferenceDefAccess().getGroup_3_1(), "rule__InstanceReferenceDef__Group_3_1__0");
					put(grammarAccess.getInstanceReferenceDefAccess().getGroup_6(), "rule__InstanceReferenceDef__Group_6__0");
					put(grammarAccess.getInstanceReferenceDefAccess().getGroup_6_1_0(), "rule__InstanceReferenceDef__Group_6_1_0__0");
					put(grammarAccess.getInstanceReferenceDefAccess().getGroup_6_1_1(), "rule__InstanceReferenceDef__Group_6_1_1__0");
					put(grammarAccess.getInstanceReferenceDefAccess().getGroup_6_1_2(), "rule__InstanceReferenceDef__Group_6_1_2__0");
					put(grammarAccess.getInstanceReferenceDefAccess().getGroup_6_1_2_2(), "rule__InstanceReferenceDef__Group_6_1_2_2__0");
					put(grammarAccess.getInstanceReferenceDefAccess().getGroup_6_1_3(), "rule__InstanceReferenceDef__Group_6_1_3__0");
					put(grammarAccess.getInstanceReferenceDefAccess().getGroup_6_1_4(), "rule__InstanceReferenceDef__Group_6_1_4__0");
					put(grammarAccess.getForeignReferenceDefAccess().getGroup(), "rule__ForeignReferenceDef__Group__0");
					put(grammarAccess.getForeignReferenceDefAccess().getGroup_4(), "rule__ForeignReferenceDef__Group_4__0");
					put(grammarAccess.getForeignReferenceDefAccess().getGroup_4_1_0(), "rule__ForeignReferenceDef__Group_4_1_0__0");
					put(grammarAccess.getForeignReferenceDefAccess().getGroup_4_1_1(), "rule__ForeignReferenceDef__Group_4_1_1__0");
					put(grammarAccess.getForeignReferenceDefAccess().getGroup_4_1_2(), "rule__ForeignReferenceDef__Group_4_1_2__0");
					put(grammarAccess.getForeignReferenceDefAccess().getGroup_4_1_2_2(), "rule__ForeignReferenceDef__Group_4_1_2_2__0");
					put(grammarAccess.getForeignReferenceDefAccess().getGroup_4_1_3(), "rule__ForeignReferenceDef__Group_4_1_3__0");
					put(grammarAccess.getForeignReferenceDefAccess().getGroup_4_1_4(), "rule__ForeignReferenceDef__Group_4_1_4__0");
					put(grammarAccess.getEClassRefStarAccess().getGroup(), "rule__EClassRefStar__Group__0");
					put(grammarAccess.getTagAccess().getGroup(), "rule__Tag__Group__0");
					put(grammarAccess.getXML_NAMEAccess().getGroup(), "rule__XML_NAME__Group__0");
					put(grammarAccess.getXML_NAMEAccess().getGroup_1(), "rule__XML_NAME__Group_1__0");
					put(grammarAccess.getNUMBERAccess().getGroup(), "rule__NUMBER__Group__0");
					put(grammarAccess.getNUMBERAccess().getGroup_1(), "rule__NUMBER__Group_1__0");
					put(grammarAccess.getFQNAccess().getGroup(), "rule__FQN__Group__0");
					put(grammarAccess.getFQNAccess().getGroup_1(), "rule__FQN__Group_1__0");
					put(grammarAccess.getModelAccess().getPackageNameAssignment_0_1(), "rule__Model__PackageNameAssignment_0_1");
					put(grammarAccess.getModelAccess().getModulesAssignment_1(), "rule__Model__ModulesAssignment_1");
					put(grammarAccess.getModuleDefAccess().getNameAssignment_1(), "rule__ModuleDef__NameAssignment_1");
					put(grammarAccess.getModuleDefAccess().getDescAssignment_2_1_0_1(), "rule__ModuleDef__DescAssignment_2_1_0_1");
					put(grammarAccess.getModuleDefAccess().getTagsAssignment_2_1_1_1(), "rule__ModuleDef__TagsAssignment_2_1_1_1");
					put(grammarAccess.getModuleDefAccess().getTagsAssignment_2_1_1_2_1(), "rule__ModuleDef__TagsAssignment_2_1_1_2_1");
					put(grammarAccess.getModuleDefAccess().getContainerAssignment_4(), "rule__ModuleDef__ContainerAssignment_4");
					put(grammarAccess.getContainerDefAccess().getNameAssignment_1(), "rule__ContainerDef__NameAssignment_1");
					put(grammarAccess.getContainerDefAccess().getRequiresIndexAssignment_2_1_0_1_0(), "rule__ContainerDef__RequiresIndexAssignment_2_1_0_1_0");
					put(grammarAccess.getContainerDefAccess().getDescAssignment_2_1_1_1(), "rule__ContainerDef__DescAssignment_2_1_1_1");
					put(grammarAccess.getContainerDefAccess().getTagsAssignment_2_1_2_1(), "rule__ContainerDef__TagsAssignment_2_1_2_1");
					put(grammarAccess.getContainerDefAccess().getTagsAssignment_2_1_2_2_1(), "rule__ContainerDef__TagsAssignment_2_1_2_2_1");
					put(grammarAccess.getContainerDefAccess().getLowerMultiplicityAssignment_2_1_3_1(), "rule__ContainerDef__LowerMultiplicityAssignment_2_1_3_1");
					put(grammarAccess.getContainerDefAccess().getUpperMultiplicityAssignment_2_1_4_1(), "rule__ContainerDef__UpperMultiplicityAssignment_2_1_4_1");
					put(grammarAccess.getContainerDefAccess().getContainerAssignment_4_0(), "rule__ContainerDef__ContainerAssignment_4_0");
					put(grammarAccess.getContainerDefAccess().getParameterAssignment_4_1(), "rule__ContainerDef__ParameterAssignment_4_1");
					put(grammarAccess.getContainerDefAccess().getReferencesAssignment_4_2(), "rule__ContainerDef__ReferencesAssignment_4_2");
					put(grammarAccess.getChoiceContainerDefAccess().getNameAssignment_1(), "rule__ChoiceContainerDef__NameAssignment_1");
					put(grammarAccess.getChoiceContainerDefAccess().getRequiresIndexAssignment_2_1_0_1_0(), "rule__ChoiceContainerDef__RequiresIndexAssignment_2_1_0_1_0");
					put(grammarAccess.getChoiceContainerDefAccess().getDescAssignment_2_1_1_1(), "rule__ChoiceContainerDef__DescAssignment_2_1_1_1");
					put(grammarAccess.getChoiceContainerDefAccess().getTagsAssignment_2_1_2_1(), "rule__ChoiceContainerDef__TagsAssignment_2_1_2_1");
					put(grammarAccess.getChoiceContainerDefAccess().getTagsAssignment_2_1_2_2_1(), "rule__ChoiceContainerDef__TagsAssignment_2_1_2_2_1");
					put(grammarAccess.getChoiceContainerDefAccess().getLowerMultiplicityAssignment_2_1_3_1(), "rule__ChoiceContainerDef__LowerMultiplicityAssignment_2_1_3_1");
					put(grammarAccess.getChoiceContainerDefAccess().getUpperMultiplicityAssignment_2_1_4_1(), "rule__ChoiceContainerDef__UpperMultiplicityAssignment_2_1_4_1");
					put(grammarAccess.getChoiceContainerDefAccess().getContainerAssignment_4(), "rule__ChoiceContainerDef__ContainerAssignment_4");
					put(grammarAccess.getParameterDefAccess().getNameAssignment_1(), "rule__ParameterDef__NameAssignment_1");
					put(grammarAccess.getParameterDefAccess().getTypeAssignment_3(), "rule__ParameterDef__TypeAssignment_3");
					put(grammarAccess.getParameterDefAccess().getRequiresIndexAssignment_4_1_0_1_0(), "rule__ParameterDef__RequiresIndexAssignment_4_1_0_1_0");
					put(grammarAccess.getParameterDefAccess().getDefaultAssignment_4_1_1_1(), "rule__ParameterDef__DefaultAssignment_4_1_1_1");
					put(grammarAccess.getParameterDefAccess().getLiteralsAssignment_4_1_2_1(), "rule__ParameterDef__LiteralsAssignment_4_1_2_1");
					put(grammarAccess.getParameterDefAccess().getDescAssignment_4_1_3_1(), "rule__ParameterDef__DescAssignment_4_1_3_1");
					put(grammarAccess.getParameterDefAccess().getTagsAssignment_4_1_4_1(), "rule__ParameterDef__TagsAssignment_4_1_4_1");
					put(grammarAccess.getParameterDefAccess().getTagsAssignment_4_1_4_2_1(), "rule__ParameterDef__TagsAssignment_4_1_4_2_1");
					put(grammarAccess.getParameterDefAccess().getLowerMultiplicityAssignment_4_1_5_1(), "rule__ParameterDef__LowerMultiplicityAssignment_4_1_5_1");
					put(grammarAccess.getParameterDefAccess().getUpperMultiplicityAssignment_4_1_6_1(), "rule__ParameterDef__UpperMultiplicityAssignment_4_1_6_1");
					put(grammarAccess.getParameterDefAccess().getMinAssignment_4_1_7_1(), "rule__ParameterDef__MinAssignment_4_1_7_1");
					put(grammarAccess.getParameterDefAccess().getMaxAssignment_4_1_8_1(), "rule__ParameterDef__MaxAssignment_4_1_8_1");
					put(grammarAccess.getReferenceDefAccess().getNameAssignment_1(), "rule__ReferenceDef__NameAssignment_1");
					put(grammarAccess.getReferenceDefAccess().getTypesAssignment_3(), "rule__ReferenceDef__TypesAssignment_3");
					put(grammarAccess.getReferenceDefAccess().getTypesAssignment_4_1(), "rule__ReferenceDef__TypesAssignment_4_1");
					put(grammarAccess.getReferenceDefAccess().getRequiresIndexAssignment_5_1_0_1_0(), "rule__ReferenceDef__RequiresIndexAssignment_5_1_0_1_0");
					put(grammarAccess.getReferenceDefAccess().getDescAssignment_5_1_1_1(), "rule__ReferenceDef__DescAssignment_5_1_1_1");
					put(grammarAccess.getReferenceDefAccess().getTagsAssignment_5_1_2_1(), "rule__ReferenceDef__TagsAssignment_5_1_2_1");
					put(grammarAccess.getReferenceDefAccess().getTagsAssignment_5_1_2_2_1(), "rule__ReferenceDef__TagsAssignment_5_1_2_2_1");
					put(grammarAccess.getReferenceDefAccess().getLowerMultiplicityAssignment_5_1_3_1(), "rule__ReferenceDef__LowerMultiplicityAssignment_5_1_3_1");
					put(grammarAccess.getReferenceDefAccess().getUpperMultiplicityAssignment_5_1_4_1(), "rule__ReferenceDef__UpperMultiplicityAssignment_5_1_4_1");
					put(grammarAccess.getInstanceReferenceDefAccess().getNameAssignment_1(), "rule__InstanceReferenceDef__NameAssignment_1");
					put(grammarAccess.getInstanceReferenceDefAccess().getContextsAssignment_3_0(), "rule__InstanceReferenceDef__ContextsAssignment_3_0");
					put(grammarAccess.getInstanceReferenceDefAccess().getContextsAssignment_3_1_1(), "rule__InstanceReferenceDef__ContextsAssignment_3_1_1");
					put(grammarAccess.getInstanceReferenceDefAccess().getDestAssignment_5(), "rule__InstanceReferenceDef__DestAssignment_5");
					put(grammarAccess.getInstanceReferenceDefAccess().getRequiresIndexAssignment_6_1_0_1_0(), "rule__InstanceReferenceDef__RequiresIndexAssignment_6_1_0_1_0");
					put(grammarAccess.getInstanceReferenceDefAccess().getDescAssignment_6_1_1_1(), "rule__InstanceReferenceDef__DescAssignment_6_1_1_1");
					put(grammarAccess.getInstanceReferenceDefAccess().getTagsAssignment_6_1_2_1(), "rule__InstanceReferenceDef__TagsAssignment_6_1_2_1");
					put(grammarAccess.getInstanceReferenceDefAccess().getTagsAssignment_6_1_2_2_1(), "rule__InstanceReferenceDef__TagsAssignment_6_1_2_2_1");
					put(grammarAccess.getInstanceReferenceDefAccess().getLowerMultiplicityAssignment_6_1_3_1(), "rule__InstanceReferenceDef__LowerMultiplicityAssignment_6_1_3_1");
					put(grammarAccess.getInstanceReferenceDefAccess().getUpperMultiplicityAssignment_6_1_4_1(), "rule__InstanceReferenceDef__UpperMultiplicityAssignment_6_1_4_1");
					put(grammarAccess.getForeignReferenceDefAccess().getNameAssignment_1(), "rule__ForeignReferenceDef__NameAssignment_1");
					put(grammarAccess.getForeignReferenceDefAccess().getDestAssignment_3(), "rule__ForeignReferenceDef__DestAssignment_3");
					put(grammarAccess.getForeignReferenceDefAccess().getRequiresIndexAssignment_4_1_0_1_0(), "rule__ForeignReferenceDef__RequiresIndexAssignment_4_1_0_1_0");
					put(grammarAccess.getForeignReferenceDefAccess().getDescAssignment_4_1_1_1(), "rule__ForeignReferenceDef__DescAssignment_4_1_1_1");
					put(grammarAccess.getForeignReferenceDefAccess().getTagsAssignment_4_1_2_1(), "rule__ForeignReferenceDef__TagsAssignment_4_1_2_1");
					put(grammarAccess.getForeignReferenceDefAccess().getTagsAssignment_4_1_2_2_1(), "rule__ForeignReferenceDef__TagsAssignment_4_1_2_2_1");
					put(grammarAccess.getForeignReferenceDefAccess().getLowerMultiplicityAssignment_4_1_3_1(), "rule__ForeignReferenceDef__LowerMultiplicityAssignment_4_1_3_1");
					put(grammarAccess.getForeignReferenceDefAccess().getUpperMultiplicityAssignment_4_1_4_1(), "rule__ForeignReferenceDef__UpperMultiplicityAssignment_4_1_4_1");
					put(grammarAccess.getEClassRefAccess().getTargetAssignment(), "rule__EClassRef__TargetAssignment");
					put(grammarAccess.getEClassRefStarAccess().getTargetAssignment_0(), "rule__EClassRefStar__TargetAssignment_0");
					put(grammarAccess.getEClassRefStarAccess().getStarAssignment_1(), "rule__EClassRefStar__StarAssignment_1");
					put(grammarAccess.getTagAccess().getKeyAssignment_0(), "rule__Tag__KeyAssignment_0");
					put(grammarAccess.getTagAccess().getValueAssignment_2(), "rule__Tag__ValueAssignment_2");
					put(grammarAccess.getModuleDefAccess().getUnorderedGroup_2_1(), "rule__ModuleDef__UnorderedGroup_2_1");
					put(grammarAccess.getContainerDefAccess().getUnorderedGroup_2_1(), "rule__ContainerDef__UnorderedGroup_2_1");
					put(grammarAccess.getChoiceContainerDefAccess().getUnorderedGroup_2_1(), "rule__ChoiceContainerDef__UnorderedGroup_2_1");
					put(grammarAccess.getParameterDefAccess().getUnorderedGroup_4_1(), "rule__ParameterDef__UnorderedGroup_4_1");
					put(grammarAccess.getReferenceDefAccess().getUnorderedGroup_5_1(), "rule__ReferenceDef__UnorderedGroup_5_1");
					put(grammarAccess.getInstanceReferenceDefAccess().getUnorderedGroup_6_1(), "rule__InstanceReferenceDef__UnorderedGroup_6_1");
					put(grammarAccess.getForeignReferenceDefAccess().getUnorderedGroup_4_1(), "rule__ForeignReferenceDef__UnorderedGroup_4_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.artop.ecuc.autosar4x.dsl.paramdef.ui.contentassist.antlr.internal.InternalParamDefDslParser typedParser = (org.artop.ecuc.autosar4x.dsl.paramdef.ui.contentassist.antlr.internal.InternalParamDefDslParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ParamDefDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ParamDefDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
