/*
* generated by Xtext
*/
package org.artop.ecuc.autosar4x.dsl.values.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.artop.ecuc.autosar4x.dsl.values.services.EcucValuesDslGrammarAccess;

public class EcucValuesDslParser extends AbstractContentAssistParser {
	
	@Inject
	private EcucValuesDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.artop.ecuc.autosar4x.dsl.values.ui.contentassist.antlr.internal.InternalEcucValuesDslParser createParser() {
		org.artop.ecuc.autosar4x.dsl.values.ui.contentassist.antlr.internal.InternalEcucValuesDslParser result = new org.artop.ecuc.autosar4x.dsl.values.ui.contentassist.antlr.internal.InternalEcucValuesDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getContainedElementAccess().getAlternatives(), "rule__ContainedElement__Alternatives");
					put(grammarAccess.getSimpleValueAccess().getAlternatives(), "rule__SimpleValue__Alternatives");
					put(grammarAccess.getVALUEAccess().getAlternatives(), "rule__VALUE__Alternatives");
					put(grammarAccess.getKEYAccess().getAlternatives(), "rule__KEY__Alternatives");
					put(grammarAccess.getBooleanLiteralAccess().getAlternatives(), "rule__BooleanLiteral__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getModelAccess().getGroup_0(), "rule__Model__Group_0__0");
					put(grammarAccess.getModuleAccess().getGroup(), "rule__Module__Group__0");
					put(grammarAccess.getModuleAccess().getGroup_3(), "rule__Module__Group_3__0");
					put(grammarAccess.getModuleAccess().getGroup_4(), "rule__Module__Group_4__0");
					put(grammarAccess.getModuleAccess().getGroup_4_1(), "rule__Module__Group_4_1__0");
					put(grammarAccess.getModuleAccess().getGroup_4_1_2(), "rule__Module__Group_4_1_2__0");
					put(grammarAccess.getContainerAccess().getGroup(), "rule__Container__Group__0");
					put(grammarAccess.getContainerAccess().getGroup_3(), "rule__Container__Group_3__0");
					put(grammarAccess.getContainerAccess().getGroup_4(), "rule__Container__Group_4__0");
					put(grammarAccess.getContainerAccess().getGroup_4_1_0(), "rule__Container__Group_4_1_0__0");
					put(grammarAccess.getContainerAccess().getGroup_4_1_1(), "rule__Container__Group_4_1_1__0");
					put(grammarAccess.getContainerAccess().getGroup_4_1_1_2(), "rule__Container__Group_4_1_1_2__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getParameterAccess().getGroup_5(), "rule__Parameter__Group_5__0");
					put(grammarAccess.getParameterAccess().getGroup_5_1_0(), "rule__Parameter__Group_5_1_0__0");
					put(grammarAccess.getParameterAccess().getGroup_5_1_1(), "rule__Parameter__Group_5_1_1__0");
					put(grammarAccess.getParameterAccess().getGroup_5_1_1_2(), "rule__Parameter__Group_5_1_1_2__0");
					put(grammarAccess.getReferenceAccess().getGroup(), "rule__Reference__Group__0");
					put(grammarAccess.getReferenceAccess().getGroup_5(), "rule__Reference__Group_5__0");
					put(grammarAccess.getReferenceAccess().getGroup_5_1_0(), "rule__Reference__Group_5_1_0__0");
					put(grammarAccess.getReferenceAccess().getGroup_5_1_1(), "rule__Reference__Group_5_1_1__0");
					put(grammarAccess.getReferenceAccess().getGroup_5_1_1_2(), "rule__Reference__Group_5_1_1_2__0");
					put(grammarAccess.getInstanceReferenceAccess().getGroup(), "rule__InstanceReference__Group__0");
					put(grammarAccess.getInstanceReferenceAccess().getGroup_5(), "rule__InstanceReference__Group_5__0");
					put(grammarAccess.getInstanceReferenceAccess().getGroup_5_1_0(), "rule__InstanceReference__Group_5_1_0__0");
					put(grammarAccess.getInstanceReferenceAccess().getGroup_5_1_1(), "rule__InstanceReference__Group_5_1_1__0");
					put(grammarAccess.getInstanceReferenceAccess().getGroup_5_1_1_2(), "rule__InstanceReference__Group_5_1_1_2__0");
					put(grammarAccess.getInstanceReferenceValueAccess().getGroup(), "rule__InstanceReferenceValue__Group__0");
					put(grammarAccess.getContextChainAccess().getGroup(), "rule__ContextChain__Group__0");
					put(grammarAccess.getContextChainAccess().getGroup_1(), "rule__ContextChain__Group_1__0");
					put(grammarAccess.getContextAccess().getGroup(), "rule__Context__Group__0");
					put(grammarAccess.getEIDAccess().getGroup(), "rule__EID__Group__0");
					put(grammarAccess.getTagAccess().getGroup(), "rule__Tag__Group__0");
					put(grammarAccess.getNUMERICAccess().getGroup(), "rule__NUMERIC__Group__0");
					put(grammarAccess.getNUMERICAccess().getGroup_2(), "rule__NUMERIC__Group_2__0");
					put(grammarAccess.getFQNAccess().getGroup(), "rule__FQN__Group__0");
					put(grammarAccess.getFQNAccess().getGroup_1(), "rule__FQN__Group_1__0");
					put(grammarAccess.getModelAccess().getPackageNameAssignment_0_1(), "rule__Model__PackageNameAssignment_0_1");
					put(grammarAccess.getModelAccess().getModulesAssignment_1(), "rule__Model__ModulesAssignment_1");
					put(grammarAccess.getModuleAccess().getDefinitionAssignment_2(), "rule__Module__DefinitionAssignment_2");
					put(grammarAccess.getModuleAccess().getShortNameAssignment_3_1(), "rule__Module__ShortNameAssignment_3_1");
					put(grammarAccess.getModuleAccess().getTagsAssignment_4_1_1(), "rule__Module__TagsAssignment_4_1_1");
					put(grammarAccess.getModuleAccess().getTagsAssignment_4_1_2_1(), "rule__Module__TagsAssignment_4_1_2_1");
					put(grammarAccess.getModuleAccess().getContainerAssignment_7(), "rule__Module__ContainerAssignment_7");
					put(grammarAccess.getContainerAccess().getDefinitionAssignment_2(), "rule__Container__DefinitionAssignment_2");
					put(grammarAccess.getContainerAccess().getShortNameAssignment_3_1(), "rule__Container__ShortNameAssignment_3_1");
					put(grammarAccess.getContainerAccess().getIndexAssignment_4_1_0_1(), "rule__Container__IndexAssignment_4_1_0_1");
					put(grammarAccess.getContainerAccess().getTagsAssignment_4_1_1_1(), "rule__Container__TagsAssignment_4_1_1_1");
					put(grammarAccess.getContainerAccess().getTagsAssignment_4_1_1_2_1(), "rule__Container__TagsAssignment_4_1_1_2_1");
					put(grammarAccess.getContainerAccess().getElementsAssignment_7(), "rule__Container__ElementsAssignment_7");
					put(grammarAccess.getParameterAccess().getDefinitionAssignment_2(), "rule__Parameter__DefinitionAssignment_2");
					put(grammarAccess.getParameterAccess().getValueAssignment_4(), "rule__Parameter__ValueAssignment_4");
					put(grammarAccess.getParameterAccess().getIndexAssignment_5_1_0_1(), "rule__Parameter__IndexAssignment_5_1_0_1");
					put(grammarAccess.getParameterAccess().getTagsAssignment_5_1_1_1(), "rule__Parameter__TagsAssignment_5_1_1_1");
					put(grammarAccess.getParameterAccess().getTagsAssignment_5_1_1_2_1(), "rule__Parameter__TagsAssignment_5_1_1_2_1");
					put(grammarAccess.getReferenceAccess().getDefinitionAssignment_2(), "rule__Reference__DefinitionAssignment_2");
					put(grammarAccess.getReferenceAccess().getValueAssignment_4(), "rule__Reference__ValueAssignment_4");
					put(grammarAccess.getReferenceAccess().getIndexAssignment_5_1_0_1(), "rule__Reference__IndexAssignment_5_1_0_1");
					put(grammarAccess.getReferenceAccess().getTagsAssignment_5_1_1_1(), "rule__Reference__TagsAssignment_5_1_1_1");
					put(grammarAccess.getReferenceAccess().getTagsAssignment_5_1_1_2_1(), "rule__Reference__TagsAssignment_5_1_1_2_1");
					put(grammarAccess.getInstanceReferenceAccess().getDefinitionAssignment_2(), "rule__InstanceReference__DefinitionAssignment_2");
					put(grammarAccess.getInstanceReferenceAccess().getValueAssignment_4(), "rule__InstanceReference__ValueAssignment_4");
					put(grammarAccess.getInstanceReferenceAccess().getIndexAssignment_5_1_0_1(), "rule__InstanceReference__IndexAssignment_5_1_0_1");
					put(grammarAccess.getInstanceReferenceAccess().getTagsAssignment_5_1_1_1(), "rule__InstanceReference__TagsAssignment_5_1_1_1");
					put(grammarAccess.getInstanceReferenceAccess().getTagsAssignment_5_1_1_2_1(), "rule__InstanceReference__TagsAssignment_5_1_1_2_1");
					put(grammarAccess.getReferenceValueAccess().getContainerAssignment(), "rule__ReferenceValue__ContainerAssignment");
					put(grammarAccess.getInstanceReferenceValueAccess().getContextsAssignment_0(), "rule__InstanceReferenceValue__ContextsAssignment_0");
					put(grammarAccess.getInstanceReferenceValueAccess().getTargetAssignment_2(), "rule__InstanceReferenceValue__TargetAssignment_2");
					put(grammarAccess.getContextChainAccess().getObjectAssignment_1_2(), "rule__ContextChain__ObjectAssignment_1_2");
					put(grammarAccess.getContextAccess().getStartAssignment_1(), "rule__Context__StartAssignment_1");
					put(grammarAccess.getStringValueAccess().getValueAssignment(), "rule__StringValue__ValueAssignment");
					put(grammarAccess.getEnumValueAccess().getLiteralAssignment(), "rule__EnumValue__LiteralAssignment");
					put(grammarAccess.getBooleanValueAccess().getValueAssignment(), "rule__BooleanValue__ValueAssignment");
					put(grammarAccess.getNumericValueAccess().getValueAssignment(), "rule__NumericValue__ValueAssignment");
					put(grammarAccess.getTagAccess().getKeyAssignment_0(), "rule__Tag__KeyAssignment_0");
					put(grammarAccess.getTagAccess().getValueAssignment_2(), "rule__Tag__ValueAssignment_2");
					put(grammarAccess.getContainerAccess().getUnorderedGroup_4_1(), "rule__Container__UnorderedGroup_4_1");
					put(grammarAccess.getParameterAccess().getUnorderedGroup_5_1(), "rule__Parameter__UnorderedGroup_5_1");
					put(grammarAccess.getReferenceAccess().getUnorderedGroup_5_1(), "rule__Reference__UnorderedGroup_5_1");
					put(grammarAccess.getInstanceReferenceAccess().getUnorderedGroup_5_1(), "rule__InstanceReference__UnorderedGroup_5_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.artop.ecuc.autosar4x.dsl.values.ui.contentassist.antlr.internal.InternalEcucValuesDslParser typedParser = (org.artop.ecuc.autosar4x.dsl.values.ui.contentassist.antlr.internal.InternalEcucValuesDslParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public EcucValuesDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EcucValuesDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
